name: simple-rule-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - certifi=2022.9.14=pyhd8ed1ab_0
  - colorama=0.4.4=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=py_0
  - more-itertools=8.5.0=py_0
  - packaging=20.4=py_0
  - pluggy=0.13.1=py37_0
  - py=1.9.0=py_0
  - pyparsing=2.4.7=py_0
  - pytest=6.1.1=py37_0
  - python_abi=3.7=1_cp37m
  - six=1.15.0=py_0
  - toml=0.10.1=py_0
  - wheel=0.35.1=py_0
  - zipp=3.4.0=pyhd3eb1b0_0

